[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

; core/ vira uma biblioteca: #include "vm.h" funciona e o vm.c é compilado
lib_extra_dirs = ${PROJECT_DIR}/..

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.1.0

build_flags = -Wall
